[global]
description=Access Pattern - 8k Blocks

[iometer]
bssplit=512/0:1k/5:2k/0:4k/0:8k/100:16k/0:32k/4:64k/0
rw=randrw
rwmixread=80
direct=1
size=20g
ioengine=windowsaio
# IOMeter defines the server loads as the following:
# iodepth=1	Linear
# iodepth=4	Very Light
# iodepth=8	Light
# iodepth=64	Moderate
# iodepth=256	Heavy
iodepth=${IODEPTH}
# log file
write_bw_log=${LOGBASE}-write-bw.log
write_io_log=${LOGBASE}-write-io.log
